// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwU_osygZsnK4FODCLEqPvqSEOlLgSm5o',
    appId: '1:518720610015:web:86f16e08c04fd44becd36a',
    messagingSenderId: '518720610015',
    projectId: 'qr-sisitt',
    authDomain: 'qr-sisitt.firebaseapp.com',
    storageBucket: 'qr-sisitt.appspot.com',
    measurementId: 'G-SJTYRG57HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANjZwIKrl2_SYXD_mMDpECze9vngb1oU',
    appId: '1:518720610015:android:1720a167585aad3decd36a',
    messagingSenderId: '518720610015',
    projectId: 'qr-sisitt',
    storageBucket: 'qr-sisitt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtXPya0gqIJVNc8MOXmeMzCmi_bDWXDs',
    appId: '1:518720610015:ios:354d3304944ec654ecd36a',
    messagingSenderId: '518720610015',
    projectId: 'qr-sisitt',
    storageBucket: 'qr-sisitt.appspot.com',
    androidClientId: '518720610015-t719m19j30efka77pec6qslulmr5mvok.apps.googleusercontent.com',
    iosClientId: '518720610015-vglq7toj8rmfemnt4sa9oqm6foj59gbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
